extends: base_config.yaml

attributes:
  dress_type:
    required: true
    data_type: string
    item_type: enum
    allowed_values: DressType
    threshold: 0.8
    in_search_context: true

  dress_silhouette:
    required: true
    data_type: string
    item_type: enum
    allowed_values: DressSilhouette
    threshold: 0.8
    in_search_context: true

  neckline:
    required: true
    data_type: string
    item_type: enum
    allowed_values: Neckline
    threshold: 0.8
    in_search_context: true

  sleeve_type:
    required: true
    data_type: string
    item_type: enum
    allowed_values: SleeveType
    threshold: 0.8
    in_search_context: true
        
  closure:
    required: true
    data_type: string
    item_type: enum
    allowed_values: Closure
    threshold: 0.8
    in_search_context: true
    
  back_design:
    required: true
    data_type: string
    item_type: string
    in_search_context: true


  styling_suggestions:
    required: true
    data_type: string
    item_type: string
    max_length: 3
    in_search_context: false
  

    