extends: base_config.yaml

attributes:
  lehenga_type:
    required: true
    data_type: string
    item_type: enum
    allowed_values: LehengaType
    threshold: 0.8
    in_search_context: true

  neckline:
    required: true
    data_type: string
    item_type: enum
    allowed_values: Neckline
    threshold: 0.8
    in_search_context: true
    
  skirt_style:
    required: true
    data_type: string
    item_type: enum
    allowed_values: LehengaSkirtStyle
    threshold: 0.8
    in_search_context: true

  sleeve_type:
    required: true
    data_type: string
    item_type: enum
    allowed_values: SleeveType
    threshold: 0.8
    in_search_context: true
        
  closure:
    required: true
    data_type: string
    item_type: enum
    allowed_values: Closure
    threshold: 0.8
    in_search_context: true
    
  blouse_design:
    required: true
    data_type: string
    item_type: enum
    allowed_values: LehengaBlouseDesign
    threshold: 0.8
    in_search_context: true

  back_design:
    required: true
    data_type: string
    item_type: string
    in_search_context: true

  dupatta_style:
    required: true
    data_type: string
    item_type: enum
    allowed_values: LehengaDupattaStyle
    threshold: 0.8
    in_search_context: true

  blouse_included:
    required: true
    data_type: string
    item_type: enum
    allowed_values: Included
    threshold: 0.8
    in_search_context: false

  dupatta_included:
    required: true
    data_type: string
    item_type: enum
    allowed_values: Included
    threshold: 0.8
    in_search_context: false

  styling_suggestions:
    required: true
    data_type: string
    item_type: string
    max_length: 3
    in_search_context: false
  

    