extends: base_config.yaml

attributes:
  required:
    - saree_type
    - primary_color
    - primary_color_detailed
    - primary_color_hex
    - secondary_colors
    - secondary_colors_detailed
    - secondary_colors_detailed_hex
    - pattern
    - border_width
    - border_design
    - border_design_details
    - pallu_design
    - material
    - length
    - width
    - weight
    - embellishment
    - embellishment_level
    - occasions
    - style
    - gender
    - age_group
    - brand
    - brand_title
    - title
    - description
    - price
    - care_instructions
    - size
    - unique_design_element
    - coordinating_items
    - blouse_included
  
  optional:
    - pre_draped
    - reversible
    - secondary_color_hexes
    - color_pairings
    - occasion_detailed
    - embellishment_detailed
    - blouse_material
    - validation_errors
    - search_context
    - text_embedding

validation_rules:
  primary_color:
    type: enum
    values: Color
    required: true

  primary_color_detailed:
    type: enum
    values: ColorDetailed
    required: true

  primary_color_hex:
    type: string
    pattern: "^#([A-Fa-f0-9]{6}|[A-Fa-f0-9]{3})$"
    required: true

  secondary_colors:
    type: list
    item_type: enum
    values: Color
    max_length: 5

  secondary_colors_detailed:
    type: list
    item_type: enum
    values: ColorDetailed
    max_length: 5

  pattern:
    type: list
    item_type: enum
    values: Pattern
    default: [OTHERS]

  saree_type:
    type: enum
    values: SareeType
    required: true

  border_width:
    type: enum
    values: BorderWidth
    required: true

  border_design:
    type: enum
    values: BorderDesign
    required: true

  border_design_details:
    type: list
    min_length: 3
    max_length: 5
    required: true

  pallu_design:
    type: enum
    values: PalluDesign
    required: true

  material:
    type: enum
    values: Material
    required: true

  length:
    type: float
    min: 4.5
    max: 9.5
    required: true
    
  width:
    type: float
    min: 0.9
    max: 1.4
    required: true
    
  weight:
    type: float
    min: 300
    max: 1000
    required: true

  embellishment:
    type: list
    item_type: enum
    values: Embellishment
    default: []

  embellishment_level:
    type: enum
    values: EmbellishmentLevel
    default: NONE

  occasions:
    type: list
    item_type: enum
    values: Occasion
    min_length: 2
    max_length: 4

  style:
    type: list
    item_type: enum
    values: Style
    min_length: 1
    max_length: 2

  gender:
    type: list
    item_type: enum
    values: Gender
    default: [WOMEN]

  age_group:
    type: list
    item_type: enum
    values: AgeGroup
    default: [ADULT]

  color_pairings:
    type: list
    item_type: string
    pattern: "^#([A-Fa-f0-9]{6})$"
    length: 5

  coordinating_items:
    type: object
    properties:
      clothing:
        type: list
        length: 5
      accessories:
        type: list
        length: 5
      footwear:
        type: list
        length: 5
      additional_apparel:
        type: list
        length: 3
      styling_suggestions:
        type: list
        length: 3

  unique_design_element:
    type: list
    min_length: 1
    max_length: 3

  price:
    type: float
    min: 0
    required: true

  size:
    type: list
    required: true

  blouse_included:
    type: boolean
    required: true

  blouse_material:
    type: enum
    values: Material
    required_if: blouse_included=true

  pre_draped:
    type: boolean
    default: false

  reversible:
    type: boolean
    default: false 