extends: base_config.yaml

attributes:
  saree_type:
    required: true
    data_type: string
    item_type: enum
    allowed_values: SareeType
    threshold: 0.8
    in_search_context: true
  
  border_width:
    required: true
    data_type: string
    item_type: enum
    allowed_values: BorderWidth
    threshold: 0.8
    in_search_context: true
  
  border_design:
    required: true
    data_type: string
    item_type: enum
    allowed_values: BorderDesign
    threshold: 0.8
    in_search_context: true
  
  border_design_details:
    required: true
    data_type: list
    item_type: string
    min_length: 3
    max_length: 5
    in_search_context: true
  
  pallu_design:
    required: true
    data_type: list
    item_type: string
    allowed_values: PalluDesign
    threshold: 0.8
    in_search_context: true

  length:
    required: true
    data_type: float
    item_type: float
    min: 0
    max: 12
    unit: "meters"
    in_search_context: false
  
  width:
    required: true
    data_type: float
    item_type: float
    min: 0.9
    max: 1.4
    unit: "meters"
    in_search_context: false
  
  weight:
    required: true
    data_type: float
    item_type: float
    min: 300
    max: 1000
    unit: "grams"
    in_search_context: false
  
  # Color Information
  color_pairings_hex:
    required: true
    data_type: list
    item_type: string
    pattern: "^#([A-Fa-f0-9]{6})$"
    length: 5
    in_search_context: false
  
  # Additional Features
  blouse_included:
    required: true
    data_type: boolean
    item_type: boolean
    default: false
    in_search_context: false
  
  blouse_material:
    required: false
    data_type: string
    item_type: enum
    allowed_values: Material
    threshold: 0.8
    in_search_context: false
  
  pre_draped:
    required: false
    data_type: boolean
    item_type: boolean
    default: false
    in_search_context: false
  
  reversible:
    required: false
    data_type: boolean
    item_type: boolean
    default: false
    in_search_context: false

  styling_suggestions:
    required: true
    data_type: string
    item_type: string
    max_length: 3
    in_search_context: false
  