extends: base_config.yaml

attributes:
  shirt_type:
    required: true
    data_type: string
    item_type: enum
    allowed_values: ShirtType
    threshold: 0.8
    in_search_context: true

  fit:
    required: true 
    data_type: string
    item_type: enum
    allowed_values: ShirtFit
    threshold: 0.8
    in_search_context: true

  collar:
    required: true
    data_type: string
    item_type: enum
    allowed_values: ShirtCollar
    threshold: 0.8
    in_search_context: true

  weave_pattern:
    required: true
    data_type: string
    item_type: enum
    allowed_values: ShirtWeave
    threshold: 0.8
    in_search_context: true

  sleeve_type:
    required: true
    data_type: string
    item_type: enum
    allowed_values: SleeveType
    threshold: 0.8
    in_search_context: true


